### ISSUE TITLE
I think that the authRedirect example not works as expected

### ISSUE THREAD

**Issue by maxidr** [JAForbes/mithril-map-router#2]
In the example of authRedirect, if it doesn't have token (! localStorage.getItem('auth_token')) anyway the controller of Home will be builded.
This is because the RealController will be builded anyway (https://github.com/JAForbes/mithril-map-router/blob/master/index.js#L7).
Maybe could build the controller if the visitor returns a value, or if the visitor returns not null?

**Comment by JAForbes** [comment]
Hi @maxidr, thank you for pointing this out.

You are right.  There may be some way to tell Mithril not to redirect and stay on the current Controller.  It is certainly worth investigating.

I think in the mithril rewrite the new router will make this library a lot less relevant, so I may wait until the release of the new version before addressing this issue.

I'd be happy to accept a pull request though if you'd like to have a go at fixing it.  I think the [redraw strategy](http://mithril.js.org/mithril.redraw.html#strategy) could be relevant here.

In any case, it would be good to mention this in the readme as some people may be fetching resources in their controllers unnecessarily.

**Comment by maxidr** [comment]
Yes, you are right about the new version of mithril. 
Anyway, we can add a kind of function to make a short circuit and avoid of instantiate the controller.

```javascript
var authRedirect = function(routeName, end){
  var token = localStorage.getItem('auth_token')
  if(!token){
    m.route('/login')
    end() // When call this function your controller is not instantiated
  }
}
```

What do you think?

**Comment by JAForbes** [comment]
I recently added the ability to hook into `onunload` in the visitor function.  Maybe we could pass an inert controller to mithril and initialize the user's controller ourselves based on a successful `onunload` of the previous route?

For an API, I'd probably prefer to make the router return a promise (optionally), and if it rejects we stay on the current route, if it resolves we initialize the matching controller?  Do you have objections to using a promise?  Or do you have reasons for preferring an `end` callback?  My main objection to `end` is avoiding custom api's, Promise's are part of the language now for better of for worse so I'd like to get behind that standard.

Does this sound ok @maxidr ?  What's your use case?  I'm yet to run into any problems with the existing behaviour, but I'd be happy to add this feature.

**Comment by maxidr** [comment]
I really like the idea of a promise!, yeah the ```end```callback is a bit weird.  The Promise is much more natural. Your idea is to use a parameter as a promise (instead of the ```end``` method)?
What will happen in the case when the promise delay? the component will not load till the promise succeed or rejected right?  The only bad point is in this case, because you could freeze the app till the promise ends and you can't show any kind of feedback.

My use case is the same that the example (```authRedirect```) and other that executes some  google analytics functions.

**Comment by JAForbes** [comment]
An example to try out the idea:

```js
var authRedirect = function(routeName, end){
  var token = localStorage.getItem('auth_token')
  var data = {}
  if(!token){
    m.route('/login')
    // When calling this function your controller is not instantiated
    return Promise.reject( ... ) 
  } else {
    return Promise.resolve( data ) // resolved value passed to the controller as the first arg
  }
}
```

- Promises wouldn't be required
- Async would keep you on the current route until it resolves/rejects (I have a rough idea how to do this)
- Because the previous route is still in place you will be able to show feedback

So the app shouldn't freeze, it'd be up to whatever logic your route has in place to show a loading state.

Does that sound okay?  I wonder if there are ergonomic issues in practice.

**Comment by maxidr** [comment]
I don't understand what you mean when say that the Promises wouldn't be required.  So in some cases we can return a simple value instead of a promise?
